package com.insula.app;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javafx.scene.image.Image;
import javafx.stage.Stage;

/**
 * The window icon, in every size the desktop might ask for.
 *
 * <p>All of them are handed over rather than one large image, because the window manager, the task
 * switcher and the dock each pick a different size, and a 256px icon scaled down to 16 by the
 * compositor loses the shape the small one was drawn to keep.
 *
 * <p>Generated by {@code scripts/gen-icon.py} from {@code branding/insula-icon.svg}; the same run
 * produces the {@code .icns} and {@code .ico} the installers use, so the window and the dock can
 * never show different marks.
 */
final class AppIcon {

    private static final Logger LOG = Logger.getLogger(AppIcon.class.getName());
    private static final int[] SIZES = {16, 24, 32, 48, 64, 128, 256};

    private AppIcon() {}

    /** The largest bundled icon, for a dialog that wants one picture rather than a set. */
    static javafx.scene.image.ImageView largeView(double size) {
        for (int candidate : new int[] {256, 128, 64}) {
            try (InputStream in = AppIcon.class.getResourceAsStream("icons/insula-" + candidate + ".png")) {
                if (in != null) {
                    javafx.scene.image.ImageView view = new javafx.scene.image.ImageView(new Image(in));
                    view.setFitWidth(size);
                    view.setFitHeight(size);
                    view.setPreserveRatio(true);
                    return view;
                }
            } catch (Exception e) {
                LOG.log(Level.FINE, "Could not load the large icon", e);
            }
        }
        return null;
    }

    /**
     * Puts the app icon on a dialog.
     *
     * <p>Dialogs own their own Stage, and it starts with no icon at all — so without this the
     * About box shows the generic Java cup while the window behind it shows ours.
     */
    static void applyTo(javafx.scene.control.Dialog<?> dialog) {
        javafx.scene.image.ImageView graphic = largeView(64);
        if (graphic != null) {
            dialog.setGraphic(graphic);
        }
        if (dialog.getDialogPane().getScene() != null
                && dialog.getDialogPane().getScene().getWindow() instanceof Stage stage) {
            applyTo(stage);
        }
    }

    static void applyTo(Stage stage) {
        List<Image> icons = new ArrayList<>();
        for (int size : SIZES) {
            String path = "icons/insula-" + size + ".png";
            try (InputStream in = AppIcon.class.getResourceAsStream(path)) {
                if (in != null) {
                    icons.add(new Image(in));
                }
            } catch (Exception e) {
                // A missing icon is cosmetic; it must never stop the window from opening.
                LOG.log(Level.FINE, "Could not load " + path, e);
            }
        }
        stage.getIcons().addAll(icons);
    }
}
