package com.insula.app;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javafx.scene.image.Image;
import javafx.stage.Stage;

/**
 * The window icon, in every size the desktop might ask for.
 *
 * <p>All of them are handed over rather than one large image, because the window manager, the task
 * switcher and the dock each pick a different size, and a 256px icon scaled down to 16 by the
 * compositor loses the shape the small one was drawn to keep.
 *
 * <p>Generated by {@code scripts/gen-icon.py} from {@code branding/insula-icon.svg}; the same run
 * produces the {@code .icns} and {@code .ico} the installers use, so the window and the dock can
 * never show different marks.
 */
final class AppIcon {

    private static final Logger LOG = Logger.getLogger(AppIcon.class.getName());
    private static final int[] SIZES = {16, 24, 32, 48, 64, 128, 256};

    private AppIcon() {}

    static void applyTo(Stage stage) {
        List<Image> icons = new ArrayList<>();
        for (int size : SIZES) {
            String path = "icons/insula-" + size + ".png";
            try (InputStream in = AppIcon.class.getResourceAsStream(path)) {
                if (in != null) {
                    icons.add(new Image(in));
                }
            } catch (Exception e) {
                // A missing icon is cosmetic; it must never stop the window from opening.
                LOG.log(Level.FINE, "Could not load " + path, e);
            }
        }
        stage.getIcons().addAll(icons);
    }
}
